@startuml
[*]--> Main_Menu
Main_Menu: <u>Entry:</u> PromptUser
Main_Menu -> Connection_Search : SelectLookForConnection
Connection_Search: <u>Entry:</u> PromptUserForInfo
Connection_Search: <u>Do:</u> SearchConnection
Connection_Search: <u>Exit:</u> DisplaySearchResult
Connection_Search -> Connection_Select
Connection_Select -> Main_Menu : GoBack
Connection_Select : <u>Entry:</u> PromptUserForId
Connection_Select : <u>Do:</u> SetSelectedConnection
Connection_Select : <u>Exit:</u> ConfirmSelectionResult
Connection_Select -> Main_Menu
Main_Menu --> Book_Trip : [SelectedConnection != null]SelectBookTrip
Book_Trip : <u>Entry:</u> PromptUser
Book_Trip : <u>Exit:</u> ConfirmBooking
Book_Trip --> Add_Reservation : SelectAddReservation
Add_Reservation : <u>Entry:</u> PromptUserForInfo
Add_Reservation : <u>Do:</u> CreateReservation
Add_Reservation : <u>Exit:</u> ConfirmReservation
Add_Reservation -> Book_Trip
Book_Trip -> Main_Menu : EndBooking
Main_Menu --> [*] : Exit
@enduml