@startuml Domain Model
skinparam style strictuml
skinparam DefaultFontName Arial
skinparam DefaultFontSize 16
skinparam DefaultFontStyle bold
skinparam ArrowThickness 2.2
hide empty members

class "Terminal" as terminal {
    - Results: List<Routes>
}

class "Routes" as routes {
    - id: UUID
    - DepartureTime: DateTime
    - ArrivalTime: DateTime
    - TrainType: String
    - DaysOfOperation: String
    - FirstClassPrice: Int
    - SecondClassPrice: Int
}

package "Database" <<Database>> {
    class "DBRoutes" as DBRoutes {
        - map<connection, Routes> routesMap
    }
    class "DBConnection" as DBConnection {
        - map<Cities, Connection> config
    }
    class "DBCities" as DBCities {
        - list<String> cities
    }
}

class "Connection" as connection {
    - /tripDuration(): Duration
    - /qtyStops(): Int
}

DBConnection "1" *-- "*" connection : "contains"
DBCities  "1" *-- "*" cities : "contains"

class "Cities" as cities {
    - name: String
}

cities "*" -- "*" cities : "Departure/Arrival"


terminal  -- DBRoutes : "accesses"

DBRoutes "1" *-- "*" routes : "contains"

(cities, cities) .. connection : "have"

connection "1" -- "1..3" routes : "use"

cities "1" -- "1" routes : "Departure"
cities "1" -- "1" routes : "Destination"













@enduml
