@startuml Sequence Diagram
skinparam sequenceMessageAlign center
title "System Sequence Diagram for Searching and Viewing Train Connections"
actor User
participant "System" as terminal

User -> terminal : accessTerminal()
terminal --> User : confirmation
loop Search for Connections
    User -> terminal : searchConnection(departure, arrival, day, time)
    terminal --> User : searchResults
    loop Sort Connections
    User -> terminal : selectSort(sortingParam)
    terminal --> User : sortedResults
    end
end
User -> terminal : end()
terminal --> User : confirmation
@enduml
